import './globals.css';
import ReactQueryWrapper from './ReactQueryWrapper';

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<title>Create App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				<ReactQueryWrapper>{children}</ReactQueryWrapper>
			</body>
		</html>
	);
}
